refactoring

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -21,6 +21,9 @@ jobs:
       - name: Install Dependencies
         run: npm install
 
+      - name: Build GitHub Action
+        run: npm run prepare || echo "No build step required"
+
       - name: Commit & Push Changes
         run: |
           git config --global user.email "actions@github.com"
